// Code generated by protoc-gen-go. DO NOT EDIT.
// source: redimo.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Table struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	AwsAccessKeyId       string   `protobuf:"bytes,2,opt,name=aws_access_key_id,json=awsAccessKeyId,proto3" json:"aws_access_key_id,omitempty"`
	AwsSecretAccessKey   string   `protobuf:"bytes,3,opt,name=aws_secret_access_key,json=awsSecretAccessKey,proto3" json:"aws_secret_access_key,omitempty"`
	AwsSessionToken      string   `protobuf:"bytes,4,opt,name=aws_session_token,json=awsSessionToken,proto3" json:"aws_session_token,omitempty"`
	AwsRegion            string   `protobuf:"bytes,5,opt,name=aws_region,json=awsRegion,proto3" json:"aws_region,omitempty"`
	EndpointOverride     string   `protobuf:"bytes,6,opt,name=endpoint_override,json=endpointOverride,proto3" json:"endpoint_override,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afd1a0befbd905a, []int{0}
}

func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Table) GetAwsAccessKeyId() string {
	if m != nil {
		return m.AwsAccessKeyId
	}
	return ""
}

func (m *Table) GetAwsSecretAccessKey() string {
	if m != nil {
		return m.AwsSecretAccessKey
	}
	return ""
}

func (m *Table) GetAwsSessionToken() string {
	if m != nil {
		return m.AwsSessionToken
	}
	return ""
}

func (m *Table) GetAwsRegion() string {
	if m != nil {
		return m.AwsRegion
	}
	return ""
}

func (m *Table) GetEndpointOverride() string {
	if m != nil {
		return m.EndpointOverride
	}
	return ""
}

type GETRequest struct {
	Table                *Table   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETRequest) Reset()         { *m = GETRequest{} }
func (m *GETRequest) String() string { return proto.CompactTextString(m) }
func (*GETRequest) ProtoMessage()    {}
func (*GETRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afd1a0befbd905a, []int{1}
}

func (m *GETRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETRequest.Unmarshal(m, b)
}
func (m *GETRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETRequest.Marshal(b, m, deterministic)
}
func (m *GETRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETRequest.Merge(m, src)
}
func (m *GETRequest) XXX_Size() int {
	return xxx_messageInfo_GETRequest.Size(m)
}
func (m *GETRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GETRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GETRequest proto.InternalMessageInfo

func (m *GETRequest) GetTable() *Table {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *GETRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GETResponse struct {
	Found                bool     `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value                *any.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETResponse) Reset()         { *m = GETResponse{} }
func (m *GETResponse) String() string { return proto.CompactTextString(m) }
func (*GETResponse) ProtoMessage()    {}
func (*GETResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afd1a0befbd905a, []int{2}
}

func (m *GETResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETResponse.Unmarshal(m, b)
}
func (m *GETResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETResponse.Marshal(b, m, deterministic)
}
func (m *GETResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETResponse.Merge(m, src)
}
func (m *GETResponse) XXX_Size() int {
	return xxx_messageInfo_GETResponse.Size(m)
}
func (m *GETResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GETResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GETResponse proto.InternalMessageInfo

func (m *GETResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *GETResponse) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type SETRequest struct {
	Table                *Table   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                *any.Any `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SETRequest) Reset()         { *m = SETRequest{} }
func (m *SETRequest) String() string { return proto.CompactTextString(m) }
func (*SETRequest) ProtoMessage()    {}
func (*SETRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afd1a0befbd905a, []int{3}
}

func (m *SETRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SETRequest.Unmarshal(m, b)
}
func (m *SETRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SETRequest.Marshal(b, m, deterministic)
}
func (m *SETRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SETRequest.Merge(m, src)
}
func (m *SETRequest) XXX_Size() int {
	return xxx_messageInfo_SETRequest.Size(m)
}
func (m *SETRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SETRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SETRequest proto.InternalMessageInfo

func (m *SETRequest) GetTable() *Table {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *SETRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SETRequest) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type SETResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SETResponse) Reset()         { *m = SETResponse{} }
func (m *SETResponse) String() string { return proto.CompactTextString(m) }
func (*SETResponse) ProtoMessage()    {}
func (*SETResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afd1a0befbd905a, []int{4}
}

func (m *SETResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SETResponse.Unmarshal(m, b)
}
func (m *SETResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SETResponse.Marshal(b, m, deterministic)
}
func (m *SETResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SETResponse.Merge(m, src)
}
func (m *SETResponse) XXX_Size() int {
	return xxx_messageInfo_SETResponse.Size(m)
}
func (m *SETResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SETResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SETResponse proto.InternalMessageInfo

type HGETRequest struct {
	Table                *Table   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Field                string   `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HGETRequest) Reset()         { *m = HGETRequest{} }
func (m *HGETRequest) String() string { return proto.CompactTextString(m) }
func (*HGETRequest) ProtoMessage()    {}
func (*HGETRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afd1a0befbd905a, []int{5}
}

func (m *HGETRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HGETRequest.Unmarshal(m, b)
}
func (m *HGETRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HGETRequest.Marshal(b, m, deterministic)
}
func (m *HGETRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HGETRequest.Merge(m, src)
}
func (m *HGETRequest) XXX_Size() int {
	return xxx_messageInfo_HGETRequest.Size(m)
}
func (m *HGETRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HGETRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HGETRequest proto.InternalMessageInfo

func (m *HGETRequest) GetTable() *Table {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *HGETRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HGETRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type HGETResponse struct {
	Found                bool     `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value                *any.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HGETResponse) Reset()         { *m = HGETResponse{} }
func (m *HGETResponse) String() string { return proto.CompactTextString(m) }
func (*HGETResponse) ProtoMessage()    {}
func (*HGETResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afd1a0befbd905a, []int{6}
}

func (m *HGETResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HGETResponse.Unmarshal(m, b)
}
func (m *HGETResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HGETResponse.Marshal(b, m, deterministic)
}
func (m *HGETResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HGETResponse.Merge(m, src)
}
func (m *HGETResponse) XXX_Size() int {
	return xxx_messageInfo_HGETResponse.Size(m)
}
func (m *HGETResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HGETResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HGETResponse proto.InternalMessageInfo

func (m *HGETResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *HGETResponse) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type HSETRequest struct {
	Table                *Table   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Field                string   `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	Value                *any.Any `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HSETRequest) Reset()         { *m = HSETRequest{} }
func (m *HSETRequest) String() string { return proto.CompactTextString(m) }
func (*HSETRequest) ProtoMessage()    {}
func (*HSETRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afd1a0befbd905a, []int{7}
}

func (m *HSETRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HSETRequest.Unmarshal(m, b)
}
func (m *HSETRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HSETRequest.Marshal(b, m, deterministic)
}
func (m *HSETRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HSETRequest.Merge(m, src)
}
func (m *HSETRequest) XXX_Size() int {
	return xxx_messageInfo_HSETRequest.Size(m)
}
func (m *HSETRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HSETRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HSETRequest proto.InternalMessageInfo

func (m *HSETRequest) GetTable() *Table {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *HSETRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HSETRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *HSETRequest) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type HSETResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HSETResponse) Reset()         { *m = HSETResponse{} }
func (m *HSETResponse) String() string { return proto.CompactTextString(m) }
func (*HSETResponse) ProtoMessage()    {}
func (*HSETResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afd1a0befbd905a, []int{8}
}

func (m *HSETResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HSETResponse.Unmarshal(m, b)
}
func (m *HSETResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HSETResponse.Marshal(b, m, deterministic)
}
func (m *HSETResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HSETResponse.Merge(m, src)
}
func (m *HSETResponse) XXX_Size() int {
	return xxx_messageInfo_HSETResponse.Size(m)
}
func (m *HSETResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HSETResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HSETResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Table)(nil), "redimo.v1.Table")
	proto.RegisterType((*GETRequest)(nil), "redimo.v1.GETRequest")
	proto.RegisterType((*GETResponse)(nil), "redimo.v1.GETResponse")
	proto.RegisterType((*SETRequest)(nil), "redimo.v1.SETRequest")
	proto.RegisterType((*SETResponse)(nil), "redimo.v1.SETResponse")
	proto.RegisterType((*HGETRequest)(nil), "redimo.v1.HGETRequest")
	proto.RegisterType((*HGETResponse)(nil), "redimo.v1.HGETResponse")
	proto.RegisterType((*HSETRequest)(nil), "redimo.v1.HSETRequest")
	proto.RegisterType((*HSETResponse)(nil), "redimo.v1.HSETResponse")
}

func init() {
	proto.RegisterFile("redimo.proto", fileDescriptor_7afd1a0befbd905a)
}

var fileDescriptor_7afd1a0befbd905a = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x65, 0x9c, 0x54, 0x64, 0x9c, 0x96, 0x74, 0xd5, 0x82, 0x89, 0x84, 0x04, 0x46, 0x42,
	0x50, 0x24, 0x5b, 0x09, 0x95, 0x38, 0x17, 0x11, 0x1a, 0xc4, 0xa1, 0x95, 0x9d, 0x13, 0x12, 0xb2,
	0xfc, 0x67, 0x1a, 0x4c, 0xd3, 0xdd, 0xb0, 0x6b, 0x3b, 0xca, 0x23, 0xf0, 0xb0, 0x9c, 0x78, 0x01,
	0xe4, 0xd9, 0xa4, 0x59, 0x05, 0x50, 0x2f, 0xe1, 0xb6, 0x33, 0xf3, 0x7d, 0x3b, 0x33, 0xbf, 0x81,
	0xae, 0xc4, 0xbc, 0xb8, 0x11, 0xfe, 0x5c, 0x8a, 0x52, 0xb0, 0xce, 0x2a, 0xaa, 0x07, 0xfd, 0xc7,
	0x53, 0x21, 0xa6, 0x33, 0x0c, 0xa8, 0x90, 0x56, 0x57, 0x41, 0xc2, 0x97, 0x5a, 0xe5, 0xfd, 0xb2,
	0xa0, 0x3d, 0x49, 0xd2, 0x19, 0xb2, 0x23, 0x68, 0x97, 0xcd, 0xc3, 0xb5, 0x9e, 0x5a, 0x2f, 0x3b,
	0xa1, 0x0e, 0xd8, 0x2b, 0x38, 0x4c, 0x16, 0x2a, 0x4e, 0xb2, 0x0c, 0x95, 0x8a, 0xaf, 0x71, 0x19,
	0x17, 0xb9, 0x7b, 0x8f, 0x14, 0x07, 0xc9, 0x42, 0x9d, 0x51, 0xfe, 0x13, 0x2e, 0x3f, 0xe6, 0x6c,
	0x00, 0xc7, 0x8d, 0x54, 0x61, 0x26, 0xb1, 0x34, 0x1c, 0xae, 0x4d, 0x72, 0x96, 0x2c, 0x54, 0x44,
	0xb5, 0x5b, 0x13, 0x3b, 0xd1, 0xbf, 0x2b, 0x54, 0xaa, 0x10, 0x3c, 0x2e, 0xc5, 0x35, 0x72, 0xb7,
	0x45, 0xf2, 0x07, 0x24, 0xa7, 0xfc, 0xa4, 0x49, 0xb3, 0x27, 0x00, 0x8d, 0x56, 0xe2, 0xb4, 0x10,
	0xdc, 0x6d, 0x93, 0xa8, 0x93, 0x2c, 0x54, 0x48, 0x09, 0xf6, 0x1a, 0x0e, 0x91, 0xe7, 0x73, 0x51,
	0xf0, 0x32, 0x16, 0x35, 0x4a, 0x59, 0xe4, 0xe8, 0xee, 0x91, 0xaa, 0xb7, 0x2e, 0x5c, 0xac, 0xf2,
	0xde, 0x07, 0x80, 0xf3, 0xd1, 0x24, 0xc4, 0xef, 0x15, 0xaa, 0x92, 0xbd, 0x30, 0x37, 0x77, 0x86,
	0x3d, 0xff, 0x96, 0x9c, 0x4f, 0x68, 0xd6, 0x2c, 0x7a, 0x60, 0x37, 0xeb, 0xe8, 0xed, 0x9b, 0xa7,
	0x77, 0x01, 0x0e, 0xfd, 0xa3, 0xe6, 0x82, 0x2b, 0x42, 0x78, 0x25, 0x2a, 0x9e, 0xd3, 0x47, 0xf7,
	0x43, 0x1d, 0xb0, 0x13, 0x68, 0xd7, 0xc9, 0xac, 0x42, 0x32, 0x3a, 0xc3, 0x23, 0x5f, 0x5f, 0xc3,
	0x5f, 0x5f, 0xc3, 0x3f, 0xe3, 0xcb, 0x50, 0x4b, 0x3c, 0x09, 0x10, 0xed, 0x60, 0xb0, 0x4d, 0x4f,
	0xfb, 0xee, 0x9e, 0xfb, 0xe0, 0x44, 0x9b, 0x25, 0xbc, 0x2f, 0xe0, 0x8c, 0x77, 0x01, 0x87, 0x68,
	0x14, 0x38, 0xcb, 0x57, 0xf7, 0xd7, 0x81, 0x77, 0x09, 0xdd, 0xf1, 0x6e, 0x99, 0xfd, 0xb0, 0xc0,
	0x19, 0x47, 0xff, 0x6d, 0xe2, 0xcd, 0x2c, 0xad, 0xbb, 0x67, 0x39, 0x80, 0xee, 0xd8, 0x80, 0x39,
	0xfc, 0x69, 0xc1, 0x7e, 0x48, 0xed, 0x23, 0x94, 0x75, 0x91, 0x21, 0x3b, 0x05, 0xfb, 0x7c, 0x34,
	0x61, 0xc7, 0xc6, 0x54, 0x1b, 0xda, 0xfd, 0x87, 0xdb, 0xe9, 0x15, 0xa5, 0x53, 0xb0, 0xa3, 0x2d,
	0x57, 0xf4, 0x77, 0x97, 0xd1, 0x9d, 0xbd, 0x85, 0x56, 0xc3, 0x9a, 0x99, 0x75, 0xe3, 0xb6, 0xfd,
	0x47, 0x7f, 0xe4, 0x0d, 0x63, 0xb4, 0x6d, 0x8c, 0xfe, 0x61, 0x34, 0x3a, 0xbe, 0x7b, 0xfe, 0xf9,
	0xd9, 0xb4, 0x28, 0xbf, 0x56, 0xa9, 0x9f, 0x89, 0x9b, 0x20, 0x4f, 0x2f, 0xa5, 0xf8, 0x86, 0x59,
	0x19, 0x8e, 0xde, 0x07, 0xda, 0x11, 0xd4, 0x83, 0x74, 0x8f, 0xc8, 0xbd, 0xf9, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0xc5, 0x32, 0x09, 0x05, 0xb0, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RedimoServiceClient is the client API for RedimoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RedimoServiceClient interface {
	GET(ctx context.Context, in *GETRequest, opts ...grpc.CallOption) (*GETResponse, error)
	SET(ctx context.Context, in *SETRequest, opts ...grpc.CallOption) (*SETResponse, error)
	HGET(ctx context.Context, in *HGETRequest, opts ...grpc.CallOption) (*HGETResponse, error)
	HSET(ctx context.Context, in *HSETRequest, opts ...grpc.CallOption) (*HSETResponse, error)
}

type redimoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedimoServiceClient(cc grpc.ClientConnInterface) RedimoServiceClient {
	return &redimoServiceClient{cc}
}

func (c *redimoServiceClient) GET(ctx context.Context, in *GETRequest, opts ...grpc.CallOption) (*GETResponse, error) {
	out := new(GETResponse)
	err := c.cc.Invoke(ctx, "/redimo.v1.RedimoService/GET", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redimoServiceClient) SET(ctx context.Context, in *SETRequest, opts ...grpc.CallOption) (*SETResponse, error) {
	out := new(SETResponse)
	err := c.cc.Invoke(ctx, "/redimo.v1.RedimoService/SET", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redimoServiceClient) HGET(ctx context.Context, in *HGETRequest, opts ...grpc.CallOption) (*HGETResponse, error) {
	out := new(HGETResponse)
	err := c.cc.Invoke(ctx, "/redimo.v1.RedimoService/HGET", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redimoServiceClient) HSET(ctx context.Context, in *HSETRequest, opts ...grpc.CallOption) (*HSETResponse, error) {
	out := new(HSETResponse)
	err := c.cc.Invoke(ctx, "/redimo.v1.RedimoService/HSET", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedimoServiceServer is the server API for RedimoService service.
type RedimoServiceServer interface {
	GET(context.Context, *GETRequest) (*GETResponse, error)
	SET(context.Context, *SETRequest) (*SETResponse, error)
	HGET(context.Context, *HGETRequest) (*HGETResponse, error)
	HSET(context.Context, *HSETRequest) (*HSETResponse, error)
}

// UnimplementedRedimoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRedimoServiceServer struct {
}

func (*UnimplementedRedimoServiceServer) GET(ctx context.Context, req *GETRequest) (*GETResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GET not implemented")
}
func (*UnimplementedRedimoServiceServer) SET(ctx context.Context, req *SETRequest) (*SETResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SET not implemented")
}
func (*UnimplementedRedimoServiceServer) HGET(ctx context.Context, req *HGETRequest) (*HGETResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HGET not implemented")
}
func (*UnimplementedRedimoServiceServer) HSET(ctx context.Context, req *HSETRequest) (*HSETResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HSET not implemented")
}

func RegisterRedimoServiceServer(s *grpc.Server, srv RedimoServiceServer) {
	s.RegisterService(&_RedimoService_serviceDesc, srv)
}

func _RedimoService_GET_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GETRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedimoServiceServer).GET(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redimo.v1.RedimoService/GET",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedimoServiceServer).GET(ctx, req.(*GETRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedimoService_SET_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SETRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedimoServiceServer).SET(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redimo.v1.RedimoService/SET",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedimoServiceServer).SET(ctx, req.(*SETRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedimoService_HGET_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HGETRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedimoServiceServer).HGET(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redimo.v1.RedimoService/HGET",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedimoServiceServer).HGET(ctx, req.(*HGETRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedimoService_HSET_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HSETRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedimoServiceServer).HSET(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redimo.v1.RedimoService/HSET",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedimoServiceServer).HSET(ctx, req.(*HSETRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RedimoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "redimo.v1.RedimoService",
	HandlerType: (*RedimoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GET",
			Handler:    _RedimoService_GET_Handler,
		},
		{
			MethodName: "SET",
			Handler:    _RedimoService_SET_Handler,
		},
		{
			MethodName: "HGET",
			Handler:    _RedimoService_HGET_Handler,
		},
		{
			MethodName: "HSET",
			Handler:    _RedimoService_HSET_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redimo.proto",
}
